import { DoughnutTrendChart } from "@/components/app-data-viz";
import { InlineQueryState } from "@/components/app-query-state";
import { PanelCard } from "@/components/app-section";
import { Badge } from "@/components/ui/badge";
import {
  formatPlatformLabel,
  summarizeCaptionLength,
  type NormalizedGeneratedContent,
} from "@/lib/orchestrator-intelligence";
import { formatCompactNumber } from "@/lib/insight-formatters";

import type { ChartData } from "chart.js";

type CopyFn = (en: string, vi: string) => string;

type PublishingWindowItem = {
  platform: string;
  windowLabel: string;
};

type LatestOutputPlatformScriptPanelsProps = {
  copy: CopyFn;
  latestGeneratedContent: NormalizedGeneratedContent;
  latestPlatformMixData: ChartData<"doughnut"> | null;
  latestPublishingWindows: PublishingWindowItem[];
};

export function LatestOutputPlatformScriptPanels({
  copy,
  latestGeneratedContent,
  latestPlatformMixData,
  latestPublishingWindows,
}: LatestOutputPlatformScriptPanelsProps) {
  return (
    <div className="grid gap-8 xl:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
      <PanelCard
        title={copy("Platform Post Mix", "Phân bổ post theo nền tảng")}
        description={copy(
          "Caption package readiness for each social platform in generated_content.platform_posts.",
          "Mức sẵn sàng gói caption cho từng nền tảng trong generated_content.platform_posts.",
        )}
      >
        {latestPlatformMixData ? (
          <DoughnutTrendChart
            data={latestPlatformMixData}
            className="bg-linear-to-br from-violet-100/55 via-card to-fuchsia-100/45 dark:from-violet-500/12 dark:via-card/90 dark:to-fuchsia-500/10"
          />
        ) : (
          <InlineQueryState
            state="empty"
            message={copy(
              "No platform post package found in generated content output.",
              "Chưa có gói bài đăng theo nền tảng trong đầu ra nội dung.",
            )}
          />
        )}

        {latestGeneratedContent.platformPosts.length > 0 ? (
          <div className="mt-4 space-y-3">
            {latestGeneratedContent.platformPosts.map((post) => (
              <div
                key={post.platform}
                className="rounded-2xl border border-border/60 bg-background/65 p-3"
              >
                <p className="text-xs font-semibold tracking-[0.12em] text-muted-foreground uppercase">
                  {formatPlatformLabel(post.platform)}
                </p>
                <p className="mt-1 text-sm text-foreground">
                  {post.caption || "--"}
                </p>
                <p className="mt-2 text-xs text-muted-foreground">
                  {copy("Caption length", "Độ dài caption")}:{" "}
                  {formatCompactNumber(summarizeCaptionLength(post.caption))}
                </p>
                <p className="mt-1 text-xs text-muted-foreground">
                  {copy("Best posting window", "Khung giờ đăng")}:{" "}
                  {post.bestPostTime || "--"}
                </p>
                <p className="mt-1 text-xs text-muted-foreground">
                  {copy("CTA", "Kêu gọi hành động (CTA)")}: {post.cta || "--"}
                </p>
                <div className="mt-2 flex flex-wrap gap-2">
                  {post.hashtags.map((tag) => (
                    <Badge
                      key={`${post.platform}-${tag}`}
                      variant="outline"
                      className="rounded-full"
                    >
                      {tag}
                    </Badge>
                  ))}
                </div>
              </div>
            ))}
          </div>
        ) : null}
      </PanelCard>

      <PanelCard
        title={copy("Script Blueprint", "Blueprint kịch bản")}
        description={copy(
          "Scene-by-scene script structure generated by the backend content agent.",
          "Cấu trúc kịch bản theo từng cảnh do content agent ở backend tạo ra.",
        )}
      >
        <div className="rounded-2xl border border-border/60 bg-background/70 p-4">
          <p className="text-xs font-semibold tracking-[0.12em] text-muted-foreground uppercase">
            {copy("Hook", "Mở bài")}
          </p>
          <p className="mt-1 text-sm text-foreground">
            {latestGeneratedContent.hook || "--"}
          </p>
        </div>

        {latestGeneratedContent.sections.length > 0 ? (
          <div className="mt-4 space-y-3">
            {latestGeneratedContent.sections.map((section) => (
              <div
                key={section.id}
                className="rounded-2xl border border-border/60 bg-background/65 p-3"
              >
                <p className="text-xs font-semibold tracking-[0.12em] text-primary uppercase">
                  {section.timestamp}
                </p>
                <p className="mt-1 text-sm font-semibold text-foreground">
                  {section.label}
                </p>
                <p className="mt-1 text-sm text-muted-foreground">
                  {section.narration || "--"}
                </p>
                <p className="mt-1 text-xs text-muted-foreground">
                  {copy("Editing notes", "Ghi chú dựng")}:{" "}
                  {section.notes || "--"}
                </p>
              </div>
            ))}
          </div>
        ) : (
          <InlineQueryState
            state="empty"
            message={copy(
              "No script sections returned in latest generated content.",
              "Chưa có các phân đoạn kịch bản trong lần tạo nội dung gần nhất.",
            )}
          />
        )}

        {latestPublishingWindows.length > 0 ? (
          <div className="mt-4 rounded-2xl border border-border/60 bg-background/65 p-3 text-xs text-muted-foreground">
            <p className="font-semibold text-foreground">
              {copy(
                "Publishing windows detected",
                "Khung giờ đăng được phát hiện",
              )}
            </p>
            <div className="mt-2 flex flex-wrap gap-2">
              {latestPublishingWindows.map((item, index) => (
                <Badge
                  key={`${item.platform}-${item.windowLabel}-${index}`}
                  variant="outline"
                  className="rounded-full"
                >
                  {item.platform}: {item.windowLabel}
                </Badge>
              ))}
            </div>
          </div>
        ) : null}
      </PanelCard>
    </div>
  );
}
